# Generated by Django 6.0.5 on 2026-09-13 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tweet",
            name="media",
            field=models.FileField(blank=True, null=True, upload_to="tweets_media/"),
        ),
        migrations.AddField(
            model_name="tweet",
            name="media_type",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="tweet",
            name="content",
            field=models.TextField(blank=True, max_length=280),
        ),
    ]
