# Generated by Django 6.0.5 on 2026-10-02 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_hashtag_tweethashtag"),
    ]

    operations = [
        migrations.AddField(
            model_name="tweet",
            name="quoted_tweet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quotes",
                to="api.tweet",
            ),
        ),
        migrations.AddField(
            model_name="tweet",
            name="views",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="bookmark",
            name="tweet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookmarks",
                to="api.tweet",
            ),
        ),
    ]
