# Generated by Django 6.0.5 on 2026-10-02 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_tweet_quoted_tweet_tweet_views_alter_bookmark_tweet"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tweet",
            name="quoted_tweet",
        ),
        migrations.RemoveField(
            model_name="tweet",
            name="views",
        ),
        migrations.AlterField(
            model_name="bookmark",
            name="tweet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookmarked_by",
                to="api.tweet",
            ),
        ),
    ]
