# Generated by Django 6.0.5 on 2026-10-03 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_remove_tweet_quoted_tweet_remove_tweet_views_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tweet",
            name="quoted_tweet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quotes",
                to="api.tweet",
            ),
        ),
    ]
